
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;

public class forgot extends javax.swing.JFrame {
String email,phone,password;
   int random=0;
    public forgot() {
        initComponents();
        lbotp.setVisible(false);
        lotp2.setVisible(false);
        tfotp.setVisible(false);
        jButton1.setVisible(false);
         jpassword.setVisible(false);
        setSize(1000, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        lbotp = new javax.swing.JLabel();
        lotp2 = new javax.swing.JLabel();
        tfotp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jpassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.setLayout(null);

        lb1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 0));
        lb1.setText("Enter Email");
        jPanel1.add(lb1);
        lb1.setBounds(40, 30, 170, 50);

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        jPanel1.add(tf1);
        tf1.setBounds(210, 40, 494, 40);

        bt1.setBackground(new java.awt.Color(255, 255, 0));
        bt1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        bt1.setForeground(new java.awt.Color(102, 51, 0));
        bt1.setText("Confirm");
        bt1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1);
        bt1.setBounds(210, 100, 260, 40);

        lbotp.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lbotp.setForeground(new java.awt.Color(255, 255, 0));
        lbotp.setText("Sending OTP.......");
        jPanel1.add(lbotp);
        lbotp.setBounds(220, 150, 200, 60);

        lotp2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lotp2.setForeground(new java.awt.Color(255, 255, 0));
        lotp2.setText("Enter OTP");
        jPanel1.add(lotp2);
        lotp2.setBounds(210, 210, 130, 40);

        tfotp.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jPanel1.add(tfotp);
        tfotp.setBounds(360, 210, 230, 50);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(640, 210, 120, 40);

        jpassword.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jpassword.setForeground(new java.awt.Color(255, 255, 0));
        jpassword.setText("Your Password is");
        jPanel1.add(jpassword);
        jpassword.setBounds(210, 270, 480, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
                
               new Thread(new Job()).start();
                
    }//GEN-LAST:event_bt1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(tfotp.getText().equals(random+"")){
            jpassword.setVisible(true);
            jpassword.setText("Your Password is:"+password);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    class Job implements Runnable{

        @Override
        public void run() {
            
                 try {
                        email = tf1.getText();
                        HttpResponse<String> res=Unirest.get("http://"+globalvariable.host+"/useremail")
                                .queryString("email",email)                                                                                                
                                .asString();
                         String result = res.getBody().toString();
                         System.out.println("result: "+ result);
                         StringTokenizer st = new StringTokenizer(result, ";");
                         while (st.hasMoreTokens()) {
                          password  = st.nextToken();                         
                         String phoneNo=st.nextToken();
                         String phone = phoneNo.substring(7, 10);
                           lbotp.setVisible(true);
                           lbotp.setText("Sending OTP to*******"+phone);
                             System.out.println("phone: "+ phone);
                             random = (int)(1111+(9999-1111)*Math.random());
                             System.out.println("random: "+ random);
                         /////////class///////////////
                         sms_sender.send(phone, "Your One Time Password is:"+random);
//                         obj.send(phone, result);
                         lotp2.setVisible(true);
                         tfotp.setVisible(true);
                         jButton1.setVisible(true);
                         }
                    } catch (UnirestException ex) {
                    ex.printStackTrace();
                    }
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jpassword;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lbotp;
    private javax.swing.JLabel lotp2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tfotp;
    // End of variables declaration//GEN-END:variables
}
