
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class singlevideopanel extends javax.swing.JPanel {

    String vtitle;
    public singlevideopanel(String vtitle) {
        initComponents();
        this.vtitle=vtitle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jphoto = new javax.swing.JLabel();
        jlecture = new javax.swing.JLabel();
        jtitle = new javax.swing.JLabel();
        jduration = new javax.swing.JLabel();
        jplay = new javax.swing.JButton();
        jdownload = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        jphoto.setText("jLabel1");
        add(jphoto);
        jphoto.setBounds(12, 0, 159, 84);

        jlecture.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jlecture.setForeground(new java.awt.Color(102, 51, 0));
        jlecture.setText("lecture no");
        add(jlecture);
        jlecture.setBounds(22, 97, 98, 16);

        jtitle.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jtitle.setForeground(new java.awt.Color(102, 51, 0));
        jtitle.setText("title");
        add(jtitle);
        jtitle.setBounds(22, 126, 98, 16);

        jduration.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jduration.setForeground(new java.awt.Color(102, 51, 0));
        jduration.setText("duration");
        add(jduration);
        jduration.setBounds(22, 155, 98, 16);

        jplay.setBackground(new java.awt.Color(102, 51, 0));
        jplay.setForeground(new java.awt.Color(255, 255, 0));
        jplay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 51), new java.awt.Color(255, 0, 0), new java.awt.Color(0, 204, 255), new java.awt.Color(0, 0, 255)));
        jplay.setEnabled(false);
        jplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jplayActionPerformed(evt);
            }
        });
        add(jplay);
        jplay.setBounds(110, 110, 40, 30);

        jdownload.setBackground(new java.awt.Color(102, 51, 0));
        jdownload.setForeground(new java.awt.Color(255, 255, 0));
        jdownload.setText("v");
        jdownload.setEnabled(false);
        jdownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdownloadActionPerformed(evt);
            }
        });
        add(jdownload);
        jdownload.setBounds(110, 150, 100, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jdownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdownloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdownloadActionPerformed

    private void jplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jplayActionPerformed
                     
    }//GEN-LAST:event_jplayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jdownload;
    public javax.swing.JLabel jduration;
    public javax.swing.JLabel jlecture;
    public javax.swing.JLabel jphoto;
    public javax.swing.JButton jplay;
    public javax.swing.JLabel jtitle;
    // End of variables declaration//GEN-END:variables
}
